composer:
    email: josiah.oberholtzer@gmail.com
    github: josiah-wolf-oberholtzer
    name: Josiah Wolf Oberholtzer
    website: https://www.josiahwolfoberholtzer.com
server_options:
    audio_bus_channel_count: 128
    block_size: 64
    buffer_count: 1024
    control_bus_channel_count: 4096
    hardware_buffer_size: null
    initial_node_id: 1000
    input_bus_channel_count: 0
    input_device: null
    input_stream_mask: false
    load_synthdefs: true
    maximum_node_count: 1024
    maximum_synthdef_count: 1024
    memory_locking: false
    memory_size: 524288
    output_bus_channel_count: 2
    output_device: null
    output_stream_mask: false
    protocol: udp
    random_number_generator_count: 64
    remote_control_volume: false
    restricted_path: null
    sample_rate: 44100
    verbosity: 0
    wire_buffer_count: 1024
    zero_configuration: false
title: Grey Wash
